-- AlterTable
ALTER TABLE `coopapplicationform` ADD COLUMN `contactAddrNo` VARCHAR(191) NULL,
    ADD COLUMN `contactDistrict` VARCHAR(191) NULL,
    ADD COLUMN `contactMoo` VARCHAR(191) NULL,
    ADD COLUMN `contactProvince` VARCHAR(191) NULL,
    ADD COLUMN `contactRoad` VARCHAR(191) NULL,
    ADD COLUMN `contactSoi` VARCHAR(191) NULL,
    ADD COLUMN `contactSubDistrict` VARCHAR(191) NULL,
    ADD COLUMN `contactZipcode` VARCHAR(191) NULL,
    ADD COLUMN `emerAddrNo` VARCHAR(191) NULL,
    ADD COLUMN `emerDistrict` VARCHAR(191) NULL,
    ADD COLUMN `emerMoo` VARCHAR(191) NULL,
    ADD COLUMN `emerProvince` VARCHAR(191) NULL,
    ADD COLUMN `emerRoad` VARCHAR(191) NULL,
    ADD COLUMN `emerSoi` VARCHAR(191) NULL,
    ADD COLUMN `emerSubDistrict` VARCHAR(191) NULL,
    ADD COLUMN `emerZipcode` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `coopt002form` ADD COLUMN `accomAddrNo` VARCHAR(191) NULL,
    ADD COLUMN `accomDistrict` VARCHAR(191) NULL,
    ADD COLUMN `accomMoo` VARCHAR(191) NULL,
    ADD COLUMN `accomProvince` VARCHAR(191) NULL,
    ADD COLUMN `accomRoad` VARCHAR(191) NULL,
    ADD COLUMN `accomSoi` VARCHAR(191) NULL,
    ADD COLUMN `accomSubDistrict` VARCHAR(191) NULL,
    ADD COLUMN `accomZipcode` VARCHAR(191) NULL,
    ADD COLUMN `emerAddrNo` VARCHAR(191) NULL,
    ADD COLUMN `emerDistrict` VARCHAR(191) NULL,
    ADD COLUMN `emerMoo` VARCHAR(191) NULL,
    ADD COLUMN `emerProvince` VARCHAR(191) NULL,
    ADD COLUMN `emerRoad` VARCHAR(191) NULL,
    ADD COLUMN `emerSoi` VARCHAR(191) NULL,
    ADD COLUMN `emerSubDistrict` VARCHAR(191) NULL,
    ADD COLUMN `emerZipcode` VARCHAR(191) NULL;
