-- CreateTable
CREATE TABLE `CoopT002Form` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `companyNameTh` VARCHAR(191) NULL,
    `companyNameEn` VARCHAR(191) NULL,
    `addressNo` VARCHAR(191) NULL,
    `moo` VARCHAR(191) NULL,
    `soi` VARCHAR(191) NULL,
    `road` VARCHAR(191) NULL,
    `subDistrict` VARCHAR(191) NULL,
    `district` VARCHAR(191) NULL,
    `province` VARCHAR(191) NULL,
    `zipcode` VARCHAR(191) NULL,
    `companyPhone` VARCHAR(191) NULL,
    `companyFax` VARCHAR(191) NULL,
    `companyEmail` VARCHAR(191) NULL,
    `managerName` VARCHAR(191) NULL,
    `managerPosition` VARCHAR(191) NULL,
    `managerPhone` VARCHAR(191) NULL,
    `managerFax` VARCHAR(191) NULL,
    `managerEmail` VARCHAR(191) NULL,
    `coordinatorType` VARCHAR(191) NULL,
    `coordName` VARCHAR(191) NULL,
    `coordPosition` VARCHAR(191) NULL,
    `coordDept` VARCHAR(191) NULL,
    `coordPhone` VARCHAR(191) NULL,
    `coordFax` VARCHAR(191) NULL,
    `coordEmail` VARCHAR(191) NULL,
    `supervisorName` VARCHAR(191) NULL,
    `supervisorPosition` VARCHAR(191) NULL,
    `supervisorDept` VARCHAR(191) NULL,
    `supervisorPhone` VARCHAR(191) NULL,
    `supervisorFax` VARCHAR(191) NULL,
    `supervisorEmail` VARCHAR(191) NULL,
    `jobPosition` VARCHAR(191) NULL,
    `jobDescription` TEXT NULL,
    `accommodationAddress` TEXT NULL,
    `accommodationPhone` VARCHAR(191) NULL,
    `emergencyName` VARCHAR(191) NULL,
    `emergencyAddress` TEXT NULL,
    `emergencyPhone` VARCHAR(191) NULL,
    `emergencyFax` VARCHAR(191) NULL,
    `emergencyEmail` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `CoopT002Form_studentId_key`(`studentId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CoopT002Form` ADD CONSTRAINT `CoopT002Form_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
