-- AlterTable
ALTER TABLE `company` ADD COLUMN `addressNo` VARCHAR(191) NULL,
    ADD COLUMN `district` VARCHAR(191) NULL,
    ADD COLUMN `fax` VARCHAR(191) NULL,
    ADD COLUMN `moo` VARCHAR(191) NULL,
    ADD COLUMN `province` VARCHAR(191) NULL,
    ADD COLUMN `road` VARCHAR(191) NULL,
    ADD COLUMN `soi` VARCHAR(191) NULL,
    ADD COLUMN `subDistrict` VARCHAR(191) NULL,
    ADD COLUMN `zipcode` VARCHAR(191) NULL;
