-- AlterTable
ALTER TABLE `document` MODIFY `type` ENUM('APPLICATION_DOC', 'T000_SIGNED', 'TRANSCRIPT', 'STUDENT_CARD', 'CITIZEN_CARD', 'CV', 'ACCEPTANCE_FORM', 'PARENTAL_CONSENT', 'OTHER') NOT NULL;
