-- AlterTable
ALTER TABLE `studentcoop` MODIFY `status` ENUM('APPLYING', 'QUALIFICATION_FAILED', 'QUALIFIED', 'WAITING_FOR_STAFF_CHECK', 'EDITS_REQUIRED', 'DOCS_APPROVED', 'REQ_LETTER_ISSUED', 'WAITING_FOR_PLACEMENT_LETTER', 'PLACEMENT_LETTER_ISSUED', 'INTERNSHIP_STARTED') NOT NULL DEFAULT 'APPLYING';
